version: '3.9'
services:
  mocking:
    container_name: mock
    build:
      context: ../../dockerfiles/mocking
    ports:
      - "8080"
    volumes:
      - ./src/app/libs/mocks:/mocks
  portal:
    container_name: app
    build:
      context: ../../
      dockerfile: ./apps/portal/dockerfiles/Dockerfile.dev
    ports:
      - 8201:4200
    volumes:
      - '/app/node_modules'
      - '../../:/app'
    depends_on:
      - mocking