version: '3.9'
services:
  watcher:
    build:
      context: ../../dockerfiles/wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./src/app/libs/mocks:/mocks
  portal:
    build:
      context: ../../
      dockerfile: ./apps/portal/dockerfiles/Dockerfile.dev
    ports:
      - 8201:4200
    volumes:
      - '/app/node_modules'
      - '../../:/app'